'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const W=960,H=600,TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rounds=[
 {name:'小狗',tag:'上海话与地域梗 · 松江最强',sprite:1,color:'#ffbf69',hp:460,quote:'侬好呀！先接我一招！',tip:'上海话与地域梗变成弹幕，瞄准你之前的位置。保持移动，留意小忧郁波纹。',win:'小狗：好啦好啦，还是一起吃饭吧。'},
 {name:'简单',tag:'文科满分 · 理科掉线',sprite:2,color:'#ffe18b',hp:650,quote:'来自昆明。论文学，我很在行。算数嘛……',tip:'文字弹幕留有缺口。算术对决时选对答案，让算错的简单自己扣血。',win:'简单：这不是算错，这是浪漫主义的取舍。'},
 {name:'陆远',tag:'逻辑三连 · 律师登场',sprite:3,color:'#87ccff',hp:600,quote:'首先，保持冷静。其次，请看证据。',tip:'首先、其次、因此：三段攻击依次落下。躲开红色区域，再抓住空隙输出。',win:'陆远：根据现有证据，本局判定你赢。'},
 {name:'元元',tag:'前任召唤 · 松鼠出没',sprite:4,color:'#d6a0ff',hp:650,quote:'我早就不想他了……你说松鼠？',tip:'回忆会折返。松鼠出现前有红色预警，避开冲刺路线，否则会受到暴击。',win:'元元：今天先不想他了，给我也来瓶雪碧。'},
 {name:'苦茶籽 × 酒神',tag:'特殊关卡 · 出双入对',sprite:6,color:'#ff91b2',hp:1000,quote:'苦茶籽：我写代码，你出拳。 酒神：谈恋爱还得加班。',tip:'共用血条，打谁都算。苦茶籽远程封路，酒神蓄力重拳；合招后一起休息。',win:'酒神：终于能躺了。 苦茶籽：走，一起。'}
];
const keys=new Set(),art=new Image(),background=new Image();art.src='characters.png';background.src='arena.png';
let effects=[];
let mode='home',stage=0,t=0,totalTime=0,last=0,shootCd=0,patternCd=1.8,cycle=0,quizCd=8,flash=0,toastTime=0,shake=0;
let player={x:480,y:470,hp:100,potions:3,inv:0},bosses=[],bullets=[],shots=[],zones=[],events=[],particles=[],floats=[],bossHp=0,quiz=null,resumeMode='playing';
let muted=false,audioContext=null,hits=0,heals=0,clearCount=0,cameo=false;
function spriteStyle(n){return `background-image:url('characters.png');background-position:${n%4*100/3}% ${Math.floor(n/4)*100}%`;}
function sound(kind){if(muted)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain(),now=audioContext.currentTime;o.connect(g);g.connect(audioContext.destination);o.type=kind==='hurt'?'sawtooth':'sine';const f={shot:550,hurt:95,heal:800,win:660,click:360}[kind]||350;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(kind==='heal'?1400:f*.6,now+.12);g.gain.setValueAtTime(kind==='shot'?.024:.065,now);g.gain.exponentialRampToValueAtTime(.001,now+.15);o.start(now);o.stop(now+.16)}catch{muted=true;updateSound()}}
function updateSound(){$('sound').textContent=muted?'♪ 关':'♪ 开';$('sound').setAttribute('aria-label',muted?'开启音效':'关闭音效');}
function say(text,duration=3){toastTime=duration;$('toast').textContent=text;$('toast').style.opacity='1';}
function roster(){$('lineup').innerHTML=rounds.map((r,i)=>`<li class="boss-card ${i===stage&&mode!=='home'?'active':''} ${i<clearCount?'done':''}"><span class="avatar" style="${spriteStyle(r.sprite)}"></span><div><h3>${r.name}</h3><p>${r.tag}</p></div><span class="number">${i<clearCount?'✓':'0'+(i+1)}</span></li>`).join('');$('progress').textContent=`${clearCount} / 5`;}
function hud(){window.SodaMusic?.sync(mode,stage);$('healAlert').hidden=!(mode==='playing'&&player.hp<=35&&player.potions>0);$('heal').classList?.toggle('urgent',mode==='playing'&&player.hp<=35&&player.potions>0);$('healHelp').textContent=player.potions===0?'本关雪碧已喝完':player.hp>=100?'生命已满 · 满血不消耗':'电脑按 E · 手机点此回血';$('hpText').textContent=`${Math.ceil(player.hp)} / 100`;$('hpFill').style.width=player.hp+'%';$('hpFill').style.background=player.hp<30?'#ff7e92':'#b7f65a';$('sodaCount').textContent='× '+player.potions;$('heal').disabled=mode!=='playing'||player.potions===0||player.hp>=100;$('bossName').textContent=rounds[stage].name;$('bossPercent').textContent=Math.max(0,Math.ceil(bossHp))+' HP';$('bossFill').style.width=Math.max(0,bossHp/rounds[stage].hp*100)+'%';$('bossHud').hidden=!['playing','quiz','paused'].includes(mode);$('pause').disabled=!['playing','quiz','paused'].includes(mode);$('pause').textContent=mode==='paused'?'▶':'Ⅱ';$('pause').setAttribute('aria-label',mode==='paused'?'继续游戏':'暂停游戏');}
function show(html){$('overlay').hidden=false;$('modal').innerHTML=html;keys.clear();$('modal').querySelector('button')?.focus({preventScroll:true});}
function home(){mode='home';clearCount=0;stage=0;player.hp=100;player.potions=3;$('roundLabel').textContent='等待入场';$('toast').style.opacity=0;roster();hud();show(`<div class="portrait-row">${[1,2,3,4,5,6].map(i=>`<div class="portrait" style="${spriteStyle(i)}"></div>`).join('')}</div><span class="overline">READY, FRIEND?</span><h1>熟人局，<br><em>开打了。</em></h1><p>六位好友，五场挑战。<br>躲开他们的梗，喝口雪碧继续打。</p><button class="primary" id="start">进入挑战 →</button><span class="small">移动 · 按住空格平 A · E 喝雪碧</span>`);$('start').onclick=()=>{void window.SodaMusic?.unlock();totalTime=0;hits=0;heals=0;intro(0)};}
function intro(index){stage=index;mode='intro';const r=rounds[stage];roster();hud();$('roundLabel').textContent=`ROUND 0${stage+1} / 05`;$('tip').textContent=r.tip;show(`<span class="overline">ROUND 0${stage+1} / 05</span><div class="portrait-row intro-portraits">${(stage===4?[5,6]:[r.sprite]).map(n=>`<div class="portrait" style="${spriteStyle(n)}"></div>`).join('')}</div><h1>${r.name}</h1><p class="quote">“${r.quote}”</p><p class="mechanic">${r.tip}</p><button class="primary" id="fight">开始切磋 →</button><span class="small">每关补满生命与 3 瓶雪碧 · 失败可重试本关</span>`);$('fight').onclick=begin;}
function begin(){void window.SodaMusic?.unlock();mode='playing';player={x:480,y:475,hp:100,potions:3,inv:1};t=0;shootCd=0;patternCd=1.5;quizCd=8;cycle=0;bossHp=rounds[stage].hp;bullets=[];shots=[];zones=[];events=[];particles=[];floats=[];effects=[];cameo=false;quiz=null;shake=0;flash=0;keys.clear();bosses=stage===4?[{x:345,y:195,sprite:5,r:30},{x:615,y:215,sprite:6,r:30}]:[{x:480,y:210,sprite:rounds[stage].sprite,r:32}];$('overlay').hidden=true;roster();hud();say('按住空格平 A · WASD 移动 · 按 E 喝雪碧回血',4);}
function drink(){if(mode!=='playing'||player.potions<1||player.hp>=100)return false;player.potions--;const amount=Math.min(34,100-player.hp);player.hp+=amount;player.inv=Math.max(player.inv,.35);heals++;sound('heal');burst(player.x,player.y,'#b7f65a',32);effect(player.x,player.y,'#b7f65a',105,1.0,'heal');floating(player.x,player.y-38,'+'+amount+' 雪碧回血','#b7f65a');say('嘶——开一瓶，继续！',1.6);hud();return true;}
function burst(x,y,c,n=10){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=30+Math.random()*130;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.3,c})}}
function floating(x,y,text,c){floats.push({x,y,text,c,life:1})}
function hurt(damage,critical=false){if(mode!=='playing'||player.inv>0)return;player.hp=Math.max(0,player.hp-damage);player.inv=.95;hits++;flash=.16;shake=critical?9:4;sound('hurt');burst(player.x,player.y,'#ff7e92',14);floating(player.x,player.y-35,critical?'暴击 -'+damage:'-'+damage,'#ff8eaa');hud();if(player.hp<=0){mode='lost';hud();show(`<span class="overline">TAKE A BREATH</span><h1>先喝口雪碧。</h1><p>${rounds[stage].name}这回略胜一筹。<br>本关可以直接重来，前面的进度还在。</p><button class="primary" id="retry">再来一局 ↻</button><button class="secondary" id="exit">返回首页</button>`);$('retry').onclick=begin;$('exit').onclick=home;}}
function damageBoss(n,x,y){if(mode!=='playing')return;bossHp=Math.max(0,bossHp-n);burst(x,y,rounds[stage].color,8);effect(x,y,rounds[stage].color,44,.28,'hit');if(bossHp<=0)win();hud();}
function win(){mode='won';clearCount=stage+1;bullets=[];zones=[];events=[];sound('win');roster();hud();show(`<span class="overline">${stage===4?'ALL CLEAR':'ROUND CLEAR'}</span><h1>${stage===4?'熟人局，<em>通关！</em>':'这局，你赢了。'}</h1><p class="quote">${rounds[stage].win}</p>${stage===4?`<div class="result-stats">${Math.floor(totalTime/60)} 分 ${Math.floor(totalTime%60)} 秒 · 喝了 ${heals} 瓶雪碧</div><p>朋友还是朋友，梗又多了几个。</p>`:'<p>下一关补满生命，雪碧也准备好了。</p>'}<button class="primary" id="next">${stage===4?'再聚一局 ↻':'下一位好友 →'}</button>`);$('next').onclick=()=>stage===4?home():intro(stage+1);}
function pause(){if(mode==='paused'){mode=resumeMode;$('overlay').hidden=true;if(mode==='quiz')renderQuiz();hud();return}if(!['playing','quiz'].includes(mode))return;resumeMode=mode;mode='paused';show('<span class="overline">TIME OUT</span><h1>歇一会儿。</h1><p>战斗已暂停，你的雪碧还在。</p><button class="primary" id="resume">继续切磋 →</button><button class="secondary" id="exit">返回首页</button>');$('resume').onclick=pause;$('exit').onclick=home;hud();}
function openQuiz(){if(mode!=='playing')return;const a=2+Math.floor(Math.random()*8),b=2+Math.floor(Math.random()*8),multiply=Math.random()>.5,answer=multiply?a*b:a+b,wrong=answer+(Math.random()>.5?2:-1);quiz={text:`${a} ${multiply?'×':'+'} ${b} = ?`,answer,wrong,options:Math.random()>.5?[answer,wrong]:[wrong,answer],remaining:7};mode='quiz';renderQuiz();hud();sound('click');}
function renderQuiz(){show(`<span class="overline">简单的算术对决 · 战斗暂停</span><h1>${quiz.text}</h1><p>简单：“我觉得是 ${quiz.wrong}，你说呢？”<br>选对答案，让算错的简单扣血。</p><div class="quiz-answers">${quiz.options.map((n,i)=>`<button class="primary" id="answer${i}">${n}<small style="display:block;font-size:12px">按 ${i+1}</small></button>`).join('')}</div><div class="quiz-timer"><i id="quizTimer"></i></div><span class="small">答错或超时不扣你的血，继续战斗。</span>`);quiz.options.forEach((n,i)=>$('answer'+i).onclick=()=>answerQuiz(n));}
function answerQuiz(n){if(mode!=='quiz')return;const correct=n===quiz.answer;mode='playing';$('overlay').hidden=true;keys.clear();quizCd=10;if(correct){floating(bosses[0].x,bosses[0].y-40,'算错了！-110','#ffe18b');say('简单：我这是……文学性计算。',3);damageBoss(110,bosses[0].x,bosses[0].y);sound('win')}else say('这次没抓住漏洞，下次再算。',2);quiz=null;hud();}
function schedule(delay,fn){events.push({at:t+delay,fn});}
function bullet(x,y,a,speed=160,extra={}){bullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:9,life:6,age:0,color:rounds[stage].color,damage:9,...extra});}
function aimed(b,spread=0,extra={}){bullet(b.x,b.y,Math.atan2(player.y-b.y,player.x-b.x)+spread,175,extra)}
function ring(b,count,offset=0,extra={}){for(let i=0;i<count;i++)bullet(b.x,b.y,i*TAU/count+offset,130,extra)}
function zone(z){zones.push({age:0,delay:1.05,duration:.3,damage:15,triggered:false,...z})}
function attack(){const b=bosses[0];cycle++;effect(b.x,b.y,rounds[stage].color,100,.65,'cast');
 if(stage===0){if(cycle%3===0){say('小狗：开心归开心，偶尔也有小忧郁。');ring(b,12,t*.15,{color:'#83b6ff',label:'…'});}else{const words=['侬好呀','外乡人','松江最强','勿要急','臭外地的','老灵额'];const word=words[cycle%words.length];say('小狗：'+word+'！',2.5);for(let i=-1;i<=1;i++)aimed(b,i*.30,{label:words[(cycle+i+words.length)%words.length],r:24,damage:8,loud:true});}patternCd=1.8;}
 if(stage===1){say(cycle%2?'简单：这段文字，有没有打动你？':'简单：这缺口是……艺术留白。',2);const gap=Math.atan2(player.y-b.y,player.x-b.x);for(let i=0;i<14;i++){const a=i*TAU/14+cycle*.19;if(Math.abs(Math.atan2(Math.sin(a-gap),Math.cos(a-gap)))>.48)bullet(b.x,b.y,a,130,{label:['诗','词','文','赋'][i%4],r:15,damage:10})}patternCd=2.3;}
 if(stage===2){say('陆远：首先，其次，因此。注意论证顺序。',3);const px=player.x,py=player.y;zone({type:'rect',x:clamp(px-58,45,800),y:110,w:116,h:440,label:'首先',delay:1.1});zone({type:'rect',x:45,y:clamp(py-43,120,450),w:870,h:86,label:'其次',delay:1.8});zone({type:'circle',x:px,y:py,r:100,label:'因此',delay:2.6,damage:18});patternCd=4;}
 if(stage===3){if(cycle%3===0){const fromLeft=player.x>480;const x=fromLeft?55:905,y=clamp(player.y,160,520);say('元元：怎么又是你……松鼠！暴击预警！',3);zone({type:'rect',x:45,y:y-37,w:870,h:74,delay:1.35,duration:.18,damage:0,label:'松鼠冲刺 · 暴击'});schedule(1.35,()=>bullet(x,y,fromLeft?0:Math.PI,580,{sprite:7,r:31,damage:26,critical:true,life:1.7}));}else{say('元元：这段回忆，怎么又绕回来了。',2);for(let i=-1;i<=1;i++)aimed(b,i*.42,{label:'回忆',r:20,returning:true,color:'#d6a0ff',damage:10});}patternCd=2.5;if(!cameo&&bossHp<rounds[stage].hp*.55){cameo=true;schedule(1,()=>{say('起哄三人组：小狗、酒神、元元——接梗啦！',3.5);for(let i=0;i<3;i++)schedule(i*.65,()=>{const fake={x:180+i*300,y:135};aimed(fake,0,{label:['小狗：侬好','酒神：接招','元元：来啦'][i],r:28,damage:8,color:['#ffbf69','#ff91b2','#d6a0ff'][i]})})})}}
 if(stage===4){const coder=bosses[0];if(cycle%3===0){say('情侣合招：苦茶籽封路，酒神准备出拳！',3);const gap=player.x<480?300:660;for(let i=0;i<11;i++){const x=70+i*82;if(Math.abs(x-gap)>115)bullet(x,130,Math.PI/2,165,{label:'{ }',r:17,color:'#67ddce',damage:10})}zone({type:'rect',x:gap-78,y:120,w:156,h:420,delay:1.9,duration:.35,damage:20,label:'酒神 · 你往哪走'});schedule(2.6,()=>say('酒神：歇会儿。 苦茶籽：好，都听你的。',2));patternCd=5.2;}else if(cycle%2===0){say('酒神：别让我动。',2);zone({type:'circle',x:clamp(player.x,90,870),y:clamp(player.y,155,500),r:95,delay:1.1,damage:18,label:'酒神 · 重拳'});patternCd=2.2;}else{say('苦茶籽：代码我来，重拳她来。',2);for(let i=-1;i<=1;i++)aimed(coder,i*.27,{label:['if','{ }','bug'][i+1],r:18,color:'#67ddce'});patternCd=2;}}
}
function step(dt){if(mode==='quiz'){quiz.remaining-=dt;$('quizTimer').style.width=clamp(quiz.remaining/7*100,0,100)+'%';if(quiz.remaining<=0)answerQuiz(null);return}if(mode!=='playing')return;t+=dt;totalTime+=dt;player.inv=Math.max(0,player.inv-dt);shootCd-=dt;patternCd-=dt;flash=Math.max(0,flash-dt);shake=Math.max(0,shake-dt*22);toastTime-=dt;if(toastTime<=0)$('toast').style.opacity='0';let dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),dy=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const norm=Math.hypot(dx,dy)||1;player.x=clamp(player.x+dx/norm*265*dt,65,895);player.y=clamp(player.y+dy/norm*265*dt,140,535);
 bosses.forEach((b,i)=>{let tx,ty;if(stage===0){tx=480+Math.sin(t*.75)*215;ty=220+Math.cos(t*.8)*80;}else if(stage===4){tx=i?610+Math.sin(t*.7)*110:315+Math.sin(t*.9)*90;ty=i?270+Math.sin(t*.5)*50:190;}else{tx=480+Math.sin(t*.55)*150;ty=205+Math.sin(t*.7)*35}const d=Math.hypot(tx-b.x,ty-b.y);if(d>1){b.x+=(tx-b.x)/d*Math.min(d,80*dt);b.y+=(ty-b.y)/d*Math.min(d,80*dt)}if(Math.hypot(b.x-player.x,b.y-player.y)<b.r+17)hurt(8);});if(mode!=='playing')return;
 if(keys.has('Space')||keys.has('KeyJ')){if(shootCd<=0){const b=bosses.reduce((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)<Math.hypot(b.x-player.x,b.y-player.y)?a:b),a=Math.atan2(b.y-player.y,b.x-player.x);shots.push({x:player.x,y:player.y-10,vx:Math.cos(a)*580,vy:Math.sin(a)*580,life:2});shootCd=.18;sound('shot')}}
 const due=events.filter(e=>e.at<=t);events=events.filter(e=>e.at>t);due.forEach(e=>e.fn());if(patternCd<=0)attack();
 for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const b of bosses){if(s.life>0&&Math.hypot(s.x-b.x,s.y-b.y)<b.r+7){s.life=0;damageBoss(12,b.x,b.y);break}}if(mode!=='playing')break;}shots=shots.filter(s=>s.life>0&&s.x>-20&&s.x<W+20&&s.y>-20&&s.y<H+20);if(mode!=='playing')return;
 for(const p of bullets){p.age+=dt;p.life-=dt;if(p.returning&&p.age>1.3&&!p.turned){p.vx*=-1.18;p.vy*=-1.18;p.turned=true;}p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.hypot(p.x-player.x,p.y-player.y)<p.r+15){hurt(p.damage,p.critical);p.life=0}if(mode!=='playing')break;}bullets=bullets.filter(p=>p.life>0&&p.x>-120&&p.x<W+120&&p.y>-120&&p.y<H+140);if(mode!=='playing')return;
 for(const z of zones){z.age+=dt;if(z.age>=z.delay){if(!z.triggered){z.triggered=true;burst(z.x+(z.w||0)/2,z.y+(z.h||0)/2,'#ff92a5',22);effect(z.x+(z.w||0)/2,z.y+(z.h||0)/2,'#ff92a5',z.r||90,.6,'slam');shake=Math.max(shake,3)}const inside=z.type==='circle'?Math.hypot(player.x-z.x,player.y-z.y)<z.r+15:player.x+15>z.x&&player.x-15<z.x+z.w&&player.y+15>z.y&&player.y-15<z.y+z.h;if(inside&&z.damage)hurt(z.damage);}if(mode!=='playing')break;}zones=zones.filter(z=>z.age<z.delay+z.duration);
 for(const f of effects)f.age+=dt;effects=effects.filter(f=>f.age<f.duration);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}particles=particles.filter(p=>p.life>0);for(const f of floats){f.life-=dt;f.y-=dt*35}floats=floats.filter(f=>f.life>0);
 if(stage===1&&mode==='playing'){quizCd-=dt;if(quizCd<=0)openQuiz()}hud();}

function effect(x,y,c,r=75,duration=.5,type='cast'){if(effects.length>100)effects.shift();effects.push({x,y,c,r,duration,type,age:0})}
function drawEffects(){for(const f of effects){const p=f.age/f.duration;ctx.save();ctx.translate(f.x,f.y);ctx.globalAlpha=(1-p)*.85;ctx.strokeStyle=f.c;ctx.fillStyle=f.c;ctx.shadowColor=f.c;ctx.shadowBlur=14;ctx.lineWidth=3*(1-p)+1;const radius=Math.max(2,f.r*(.15+p*.85));ctx.beginPath();ctx.arc(0,0,radius,0,TAU);ctx.stroke();if(f.type==='heal'){ctx.beginPath();ctx.arc(0,0,radius*.65,0,TAU);ctx.stroke();for(let i=0;i<8;i++){const a=i*TAU/8;ctx.beginPath();ctx.arc(Math.cos(a)*radius,Math.sin(a)*radius-25*p,3+3*p,0,TAU);ctx.stroke()}}else if(f.type==='hit'||f.type==='slam'){for(let i=0;i<8;i++){const a=i*TAU/8;ctx.beginPath();ctx.moveTo(Math.cos(a)*radius*.4,Math.sin(a)*radius*.4);ctx.lineTo(Math.cos(a)*radius,Math.sin(a)*radius);ctx.stroke()}}else{ctx.rotate(p*1.7);ctx.setLineDash([8,10]);ctx.strokeRect(-radius*.65,-radius*.65,radius*1.3,radius*1.3)}ctx.restore()}}

function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function base(){if(background.complete&&background.naturalWidth){ctx.drawImage(background,0,0,W,H);ctx.fillStyle='rgba(5,14,27,.23)';ctx.fillRect(0,0,W,H);ctx.strokeStyle=['#f4bd78','#e5d191','#9dcfff','#cca8ed','#ffa6bf'][stage];ctx.globalAlpha=.55;ctx.lineWidth=2;ctx.strokeRect(40,105,880,450);ctx.globalAlpha=1;return;}ctx.fillStyle='#101e30';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#1b3045';ctx.lineWidth=1;for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='#38534a';ctx.lineWidth=2;ctx.strokeRect(40,105,880,450);ctx.setLineDash([8,12]);ctx.strokeStyle='#29423f';ctx.beginPath();ctx.arc(480,330,150,0,TAU);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#203647';ctx.font='bold 40px system-ui';ctx.textAlign='center';ctx.fillText('FRIENDS ONLY',480,344);ctx.strokeStyle='#b7f65a';for(const [x,y,sx,sy] of [[40,105,1,1],[920,105,-1,1],[40,555,1,-1],[920,555,-1,-1]]){ctx.beginPath();ctx.moveTo(x+sx*22,y);ctx.lineTo(x,y);ctx.lineTo(x,y+sy*22);ctx.stroke()}}
function character(x,y,n,name,color,size=70){const h=size*1.17;ctx.save();ctx.shadowColor=color;ctx.shadowBlur=14;rounded(x-size/2,y-h*.68,size,h,14,'#17293a',color);ctx.shadowBlur=0;ctx.beginPath();ctx.roundRect(x-size/2+2,y-h*.68+2,size-4,h-4,12);ctx.clip();if(art.complete&&art.naturalWidth){const cw=art.naturalWidth/4,ch=art.naturalHeight/2;ctx.drawImage(art,n%4*cw,Math.floor(n/4)*ch,cw,ch,x-size/2,y-h*.68,size,h)}else{ctx.fillStyle=color;ctx.font='bold 24px system-ui';ctx.textAlign='center';ctx.fillText(name.slice(0,1),x,y)}ctx.restore();ctx.font='bold 13px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(name,x,y+h*.32+20);}
function draw(){ctx.save();base();if(shake&&mode==='playing')ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);if(mode==='home'){character(480,435,0,'你','#b7f65a',76);ctx.restore();return}for(const z of zones){const live=z.age>=z.delay,alpha=live?.7:.15+.1*Math.sin(z.age*15);ctx.fillStyle=`rgba(255,105,134,${alpha})`;ctx.strokeStyle=live?'#ffd2db':'#ff819c';ctx.lineWidth=2;ctx.setLineDash(live?[]:[7,5]);ctx.beginPath();if(z.type==='circle')ctx.arc(z.x,z.y,z.r,0,TAU);else ctx.rect(z.x,z.y,z.w,z.h);ctx.fill();ctx.stroke();ctx.setLineDash([]);ctx.font='bold 16px "Microsoft YaHei"';ctx.fillStyle='#ffbccd';ctx.textAlign='center';ctx.fillText(z.label,z.x+(z.w||0)/2,z.y+(z.h?z.h/2:0));}
 drawEffects();bosses.forEach((b,i)=>character(b.x,b.y,b.sprite,stage===4?(i?'酒神':'苦茶籽'):rounds[stage].name,stage===4?(i?'#ff91b2':'#67ddce'):rounds[stage].color));
 for(const s of shots){ctx.strokeStyle='#b7f65a88';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x-s.vx*.035,s.y-s.vy*.035);ctx.lineTo(s.x,s.y);ctx.stroke();ctx.shadowColor='#b7f65a';ctx.shadowBlur=16;ctx.fillStyle='#d6ffad';ctx.beginPath();ctx.arc(s.x,s.y,6,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#77caa3';ctx.beginPath();ctx.arc(s.x,s.y,10,0,TAU);ctx.stroke();}
 for(const p of bullets){ctx.save();ctx.strokeStyle=p.color+'88';ctx.lineWidth=p.critical?14:3;ctx.shadowColor=p.color;ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(p.x-p.vx*.075,p.y-p.vy*.075);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();if(p.sprite===7){character(p.x,p.y,7,'松鼠 · 暴击','#ffbf69',62);continue}if(p.label){ctx.font=(p.loud?'bold 19px':'bold 15px')+' "Microsoft YaHei",sans-serif';const width=ctx.measureText(p.label).width+22;rounded(p.x-width/2,p.y-15,width,30,8,'#273047',p.color);ctx.fillStyle=p.color;ctx.textAlign='center';ctx.fillText(p.label,p.x,p.y+5)}else{ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill()}}
 ctx.globalAlpha=player.inv>0&&Math.floor(player.inv*12)%2===0?.48:1;character(player.x,player.y,0,'你','#b7f65a',56);ctx.globalAlpha=1;ctx.beginPath();ctx.arc(player.x,player.y,5,0,TAU);ctx.fillStyle='#fff';ctx.fill();
 for(const p of particles){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;for(const f of floats){ctx.globalAlpha=clamp(f.life*2,0,1);ctx.fillStyle=f.c;ctx.font='bold 19px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;if(flash>0){ctx.fillStyle=`rgba(255,65,95,${flash})`;ctx.fillRect(0,0,W,H)}ctx.restore();}
function frame(now){if(!last)last=now;const dt=Math.min((now-last)/1000,.05);last=now;step(dt);draw();requestAnimationFrame(frame)}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&['playing','quiz'].includes(mode))e.preventDefault();if(e.code==='Escape'&&!e.repeat){pause();return}if(mode==='quiz'&&!e.repeat){if(e.code==='Digit1')answerQuiz(quiz.options[0]);if(e.code==='Digit2')answerQuiz(quiz.options[1]);return}if(mode!=='playing')return;keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)drink();});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(['playing','quiz'].includes(mode))pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(['playing','quiz'].includes(mode))pause()}});
document.querySelectorAll('[data-key]').forEach(el=>{el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);if(mode==='playing')keys.add(el.dataset.key)});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,()=>keys.delete(el.dataset.key));});
$('heal').onclick=drink;$('pause').onclick=pause;$('sound').onclick=()=>{muted=!muted;updateSound();if(!muted)sound('click')};
if(document.modelContext?.registerTool){const controller=new AbortController();for(const tool of [{name:'get_game_status',title:'查看当前挑战',description:'Read current round, health, soda supplies, and play state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state:mode,round:rounds[stage].name,health:player.hp,soda:player.potions,cleared:clearCount})},{name:'drink_soda',title:'喝雪碧回血',description:'Use one soda during active combat to heal. Fails when unavailable or health is full.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('No arguments accepted');if(!drink())throw new Error('Soda unavailable');return{health:player.hp,soda:player.potions}}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
$('music').onclick=()=>window.SodaMusic?.toggle();$('volume').oninput=e=>window.SodaMusic?.setVolume(e.target.value);updateSound();home();requestAnimationFrame(frame);
